<?php

declare(strict_types=1);

namespace Manifesto\Mfd\Step;

use Manifesto\Mfd\Component\ComponentGenerator;

/**
 * Custom theme from core's starterkit, the example card component, and the card
 * placed on the front page so the site story and the ExistingSite test have a
 * real Drupal render to check.
 */
final class ThemeStep implements Step
{
    private const CONTENT = '{{ page.content }}';

    public function name(): string
    {
        return 'theme';
    }

    public function plan(Context $context): array
    {
        $c = $context->config;

        return [
            sprintf(
                'ddev exec vendor/bin/dr generate-theme %s --name "%s" --path themes/custom',
                $c->theme,
                $c->themeLabel,
            ),
            sprintf('write web/themes/custom/%s/components/card/ (the example component)', $c->theme),
            sprintf(
                'write web/themes/custom/%s/templates/layout/page--front.html.twig (includes the card)',
                $c->theme,
            ),
            sprintf('ddev drush theme:enable %s; set it as the default theme; clear caches', $c->theme),
        ];
    }

    public function run(Context $context): void
    {
        $theme = $context->config->theme;
        $themeDir = $context->path('web/themes/custom/' . $theme);
        $dir = $context->projectDir;

        // Drupal 11.4: vendor/bin/dr is the generator; core/scripts/drupal is deprecated.
        if (!is_file("$themeDir/$theme.info.yml")) {
            $context->shell->run(
                [
                    'ddev', 'exec', 'vendor/bin/dr', 'generate-theme', $theme,
                    '--name', $context->config->themeLabel, '--path', 'themes/custom',
                ],
                $dir,
            );
        }
        if (!is_file("$themeDir/$theme.info.yml")) {
            throw new \RuntimeException("the theme generator did not create $themeDir/$theme.info.yml");
        }
        $this->tidyInfoFile("$themeDir/$theme.info.yml", $context->config->themeLabel);
        $this->addSiteBrandingTargetSize($themeDir, $theme);
        if (!is_dir("$themeDir/components/card")) {
            (new ComponentGenerator())->generate($themeDir, 'card');
        }
        $this->placeCardOnFrontPage($themeDir . '/templates/layout', $theme);
        $context->shell->run(['ddev', 'drush', 'theme:enable', $theme, '-y'], $dir);
        $context->shell->run(['ddev', 'drush', 'config:set', 'system.theme', 'default', $theme, '-y'], $dir);
        $context->shell->run(['ddev', 'drush', 'cr'], $dir);
    }

    /**
     * drupal/coder warns on the starterkit's empty description and its `version` key (drupal.org
     * packaging adds one). Give the theme a description and drop the version. Safe to rerun.
     */
    private function tidyInfoFile(string $infoFile, string $themeLabel): void
    {
        $info = self::read($infoFile);
        $description = sprintf("description: '%s'", str_replace("'", "''", $themeLabel . ' theme, generated by mfd.'));
        $tidy = (string) preg_replace(['/^version: .*\n/m', "/^description: ''$/m"], ['', $description], $info);
        if ($tidy !== $info) {
            self::write($infoFile, $tidy);
        }
    }

    /**
     * The starterkit's site-name link is shorter than 24px, which fails WCAG 2.2 AA 2.5.8 and
     * every design review. Ship a small site-branding library that fixes it. Safe to rerun.
     */
    private function addSiteBrandingTargetSize(string $themeDir, string $theme): void
    {
        $css = $themeDir . '/css/components/site-branding.css';
        if (!is_file($css)) {
            if (!is_dir(dirname($css)) && !mkdir(dirname($css), 0777, true)) {
                throw new \RuntimeException('could not create ' . dirname($css));
            }
            self::write($css, <<<'CSS'
                /* WCAG 2.2 AA 2.5.8: links need a target of at least 24 by 24 CSS pixels. */
                .site-name a {
                  display: inline-flex;
                  align-items: center;
                  min-block-size: 24px;
                  min-inline-size: 24px;
                }

                CSS);
        }

        $librariesFile = "$themeDir/$theme.libraries.yml";
        $libraries = is_file($librariesFile) ? self::read($librariesFile) : '';
        if (!str_contains($libraries, "\nsite-branding:\n") && !str_starts_with($libraries, "site-branding:\n")) {
            $separator = $libraries === '' || str_ends_with($libraries, "\n") ? '' : "\n";
            self::write($librariesFile, $libraries . $separator
                . "\nsite-branding:\n  css:\n    component:\n      css/components/site-branding.css: {}\n");
        }

        $infoFile = "$themeDir/$theme.info.yml";
        $info = self::read($infoFile);
        $entry = "  - $theme/site-branding\n";
        if (!str_contains($info, $entry)) {
            $withEntry = preg_replace('/^libraries:\n/m', "libraries:\n" . $entry, $info, 1, $count);
            self::write($infoFile, $count === 1 ? (string) $withEntry : $info . "libraries:\n" . $entry);
        }
    }

    private static function read(string $file): string
    {
        $text = file_get_contents($file);
        if ($text === false) {
            throw new \RuntimeException('could not read ' . $file);
        }

        return $text;
    }

    private static function write(string $file, string $text): void
    {
        if (file_put_contents($file, $text) !== strlen($text)) {
            throw new \RuntimeException('could not write ' . $file);
        }
    }

    /** Copy the generated page template to page--front and include the card just before the main content. */
    private function placeCardOnFrontPage(string $layoutDir, string $theme): void
    {
        $front = $layoutDir . '/page--front.html.twig';
        if (is_file($front)) {
            return;
        }
        $page = $layoutDir . '/page.html.twig';
        $text = is_file($page) ? (string) file_get_contents($page) : '';
        $position = strpos($text, self::CONTENT);
        if ($position === false) {
            throw new \RuntimeException(
                $page . ' has no ' . self::CONTENT . '; cannot place the example card on the front page',
            );
        }
        $card = sprintf("{{ include('%s:card', { heading: 'Welcome' }, with_context = false) }}\n      ", $theme);
        file_put_contents($front, substr_replace($text, $card . self::CONTENT, $position, strlen(self::CONTENT)));
    }
}
