<?php

declare(strict_types=1);

namespace Manifesto\Mfd\Tests\Unit\Step;

use Manifesto\Mfd\Step\DrupalStep;
use Manifesto\Mfd\Step\ThemeStep;
use Manifesto\Mfd\Tests\Support\NewCommandTestCase;
use Symfony\Component\Console\Tester\CommandTester;

final class ThemeStepTest extends NewCommandTestCase
{
    /** @param array<string, mixed> $input */
    private function theme(array $input = ['name' => 'acme']): CommandTester
    {
        return $this->newProject($input, [new DrupalStep(), new ThemeStep()]);
    }

    public function testGeneratesTheThemeAddsTheCardAndSetsTheDefault(): void
    {
        $tester = $this->theme(['name' => 'acme-corp', '--theme-label' => 'Acme & Co']);

        self::assertSame(0, $tester->getStatusCode(), $tester->getDisplay());
        self::assertContains(
            'ddev exec vendor/bin/dr generate-theme acme_corp --name Acme & Co --path themes/custom',
            $this->shell->calls,
        );
        $card = $this->project('acme-corp') . '/web/themes/custom/acme_corp/components/card';
        self::assertStringContainsString('examples:', (string) file_get_contents($card . '/card.component.yml'));
        self::assertStringContainsString('data-qa="card"', (string) file_get_contents($card . '/card.twig'));
        self::assertContains('ddev drush theme:enable acme_corp -y', $this->shell->calls);
        self::assertContains('ddev drush config:set system.theme default acme_corp -y', $this->shell->calls);
        self::assertContains('ddev drush cr', $this->shell->calls);
    }

    /** drupal/coder warns on an empty description and on a `version` key; the starterkit writes both. */
    public function testTheInfoFileHasADescriptionAndNoVersion(): void
    {
        $this->theme(['name' => 'acme-corp', '--theme-label' => 'Acme & Co']);
        $info = (string) file_get_contents(
            $this->project('acme-corp') . '/web/themes/custom/acme_corp/acme_corp.info.yml',
        );

        self::assertStringContainsString("description: 'Acme & Co theme, generated by mfd.'\n", $info);
        self::assertStringNotContainsString("description: ''", $info);
        self::assertDoesNotMatchRegularExpression('/^version:/m', $info);
        self::assertStringContainsString("name: 'Acme & Co'\n", $info);
    }

    /** The starterkit's site-name link is shorter than 24px, which fails WCAG 2.2 AA 2.5.8 (target size). */
    public function testTheSiteNameLinkMeetsTheMinimumTargetSize(): void
    {
        $this->theme();
        $themeDir = $this->project('acme') . '/web/themes/custom/acme';

        $css = (string) file_get_contents($themeDir . '/css/components/site-branding.css');
        self::assertStringContainsString('.site-name a', $css);
        self::assertStringContainsString('min-block-size: 24px', $css);
        self::assertStringContainsString(
            "site-branding:\n  css:\n    component:\n      css/components/site-branding.css: {}\n",
            (string) file_get_contents($themeDir . '/acme.libraries.yml'),
        );
        self::assertStringContainsString(
            "libraries:\n  - acme/site-branding\n",
            (string) file_get_contents($themeDir . '/acme.info.yml'),
        );
    }

    public function testARerunDoesNotDuplicateTheThemeFixes(): void
    {
        $this->shell->failOn('drush theme:enable');
        $this->theme();
        $this->shell->clearFailures();
        $this->theme();
        $themeDir = $this->project('acme') . '/web/themes/custom/acme';
        $info = (string) file_get_contents($themeDir . '/acme.info.yml');
        $libraries = (string) file_get_contents($themeDir . '/acme.libraries.yml');

        self::assertSame(1, substr_count($info, 'acme/site-branding'));
        self::assertSame(1, substr_count($libraries, 'site-branding:'));
        self::assertSame(1, substr_count($info, 'description:'));
    }

    public function testFrontPageTemplateIncludesTheCardBeforeThePageContent(): void
    {
        $this->theme();
        $front = (string) file_get_contents(
            $this->project('acme') . '/web/themes/custom/acme/templates/layout/page--front.html.twig',
        );

        self::assertStringContainsString(
            "{{ include('acme:card', { heading: 'Welcome' }, with_context = false) }}",
            $front,
        );
        self::assertLessThan(strpos($front, '{{ page.content }}'), strpos($front, 'acme:card'));
    }

    public function testFailsClearlyWhenThePageTemplateHasNoContentRegion(): void
    {
        $this->shell->failOn('drush theme:enable');
        $this->theme();
        $layout = $this->project('acme') . '/web/themes/custom/acme/templates/layout';
        unlink($layout . '/page--front.html.twig');
        file_put_contents($layout . '/page.html.twig', "<main></main>\n");
        $this->shell->clearFailures();
        $tester = $this->theme();

        self::assertSame(1, $tester->getStatusCode());
        self::assertStringContainsString('page.content', $tester->getDisplay());
    }

    public function testARerunKeepsAnEditedCardAndDoesNotRegenerateTheTheme(): void
    {
        $this->shell->failOn('drush theme:enable');
        $this->theme();
        $twig = $this->project('acme') . '/web/themes/custom/acme/components/card/card.twig';
        file_put_contents($twig, 'edited');
        $this->shell->clearFailures();
        $this->shell->calls = [];
        $tester = $this->theme();

        self::assertSame(0, $tester->getStatusCode(), $tester->getDisplay());
        self::assertSame('edited', file_get_contents($twig));
        self::assertSame([], $this->shell->callsStartingWith('ddev exec vendor/bin/dr generate-theme'));
    }
}
